# Generated by Django 4.2.5 on 2023-10-18 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestTableManager',
        ),
    ]
