# Generated by Django 4.2.5 on 2023-10-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerServices',
            fields=[
                ('category_id', models.IntegerField()),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('subcategory', models.CharField(max_length=256)),
                ('progress', models.SmallIntegerField(default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('poster_id', models.IntegerField()),
                ('poster_name', models.CharField(max_length=128, null=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('is_pending_mod', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('href', models.CharField(max_length=160)),
                ('paragraph', models.TextField()),
            ],
        ),
    ]
