# Generated by Django 4.2.5 on 2023-10-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillboardAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='careerservices',
            table='Career_Services',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='Categories',
        ),
    ]
