# Generated by Django 4.2.5 on 2023-10-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillboardAPI', '0002_alter_careerservices_table_alter_categories_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('subcategory', models.CharField(max_length=256)),
                ('progress', models.SmallIntegerField(default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('poster_id', models.IntegerField()),
                ('poster_name', models.CharField(max_length=128, null=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('is_pending_mod', models.BooleanField(default=False)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Posts',
            },
        ),
        migrations.DeleteModel(
            name='CareerServices',
        ),
    ]
