# Generated by Django 4.0 on 2023-11-29 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BillboardAPI', '0004_comments_disallowed_users_user_upvotes_users_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='post_count',
            new_name='comment_count',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment_count',
        ),
    ]
